spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:db}:${DB_PORT:3306}/${DB_NAME:serverwatch}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:sw}
    password: ${DB_PASS:swpass}

  jpa:
    hibernate:
      ddl-auto: update